export enum WorkspacePermissions {
  EDIT_WORKSPACE = 'EDIT_WORKSPACE',
  DELETE_WORKSPACE = 'DELETE_WORKSPACE',
  ADD_USER_TO_WORKSPACE = 'ADD_USER_TO_WORKSPACE',
  UPDATE_USER_ROLE = 'UPDATE_USER_ROLE',
  REMOVE_USER_FROM_WORKSPACE = 'REMOVE_USER_FROM_WORKSPACE',
}
